## Building a GPT

Companion notebook to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT.

In [8]:
from datasets import load_dataset

ds = load_dataset("Salesforce/wikitext", "wikitext-2-raw-v1")

all_text = []
for split in ["train", "validation", "test"]:
    all_text.extend(ds[split]["text"])

all_text = [x for x in all_text if x.strip()]

text = "\n".join(all_text)

with open("input.txt", "w", encoding="utf-8") as f:
    f.write(text)

print("saved input.txt")
print("num chars:", len(text))

saved input.txt
num chars: 13349880


In [9]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [10]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  13349880


In [11]:
# let's look at the first 1000 characters
print(text[:1000])

 = Valkyria Chronicles III = 

 Senjō no Valkyria 3 : Unrecorded Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " Calamaty Raven " . 

 The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more forgiving for series ne

In [12]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz|}~“”¡¢£¥§©°±²³´µ·º½¾¿ÁÄÅÆÇÉÍÎÑÓÖ×ØÚÜÞßàáâãäåæçèéêëìíîïðñòóôöøùúûüýþĀāăąćČčĐđĒēĔĕėęěğħīİıĽŁłńŌōœřŚśŞşŠšţũūůųźŻżŽžơưǎǐǔǜȘșțȯɐɑɒɔəɛɜɡɢɪɫɳɽɾʁʃʊʋʒʔʕʲʻʼʾʿˈˌː̥̯͍́̃̍͘ΑΔΚΝΠΤΦΧΩάέήίαβγδεηθικλμνξοπρςστυχψωόύώАБВГКПРСУХЯавгдежзийклмнопрстухцшъыьюяєֵֶָֹּאבגהוזחילםמןנסףפצרשתءأإابةتثجحخدذرسشصعفقكلمنهويڠܐܕܗܝܠܢܬܲܵंअईकगणतदनपबमयरलवषसहािुूेैो्আলহা্ਅਲਹਾੁੱഅളഹാ്กคงชซญฐณดตนบปพภมยรลวศษสหอฮะัาิีึเแไ็่้๊์ဂစဇတနပမရလအာို္်ြွ၁၂၇၈ႠႢႣႨႬႵႿაბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰჱჲჳჴჵჶჷჸჹჺ჻ᵻḍḏḤḥḷṃṅṇṛṣṭṯạảấầẩậắễệịọỏỗộớứửữỳỹἀἰὀὁὑ​‐‑–—―‘’“”„†‡•…′″⁄₣₤₩€₱₹⅓⅔→−≡≤①☉☫♀♭♯⚳〈〉〜あいうおかがきぎくぐけこごさしすずぜただちっつとなにのはばひふほまみめもゃゆょらりるれわをんァアィイゥェエォオカガキクグゲコサシジスズセタダチッツテデトドナニネノハバパフブプヘベマミムモャュョラリルレロンヴ・ー一七下世丙中为主乃之乙九二云人今付伊似作侗依信傳儚充光全八六兵其具円再出判利制刷前剛劇劉助動勢包化北十千华南印厂去古可台史同名君吳周命和咲唐善四國園圣在坂型堂堤場塘士夕大天夫奈套女妙姚子孟学學守安宋完宗定宝宫寝寶寺小少尾山岳川州巳市師平广庆府座廬建开式張彌彩影彼征律後御微德心必忠思愛憑憶應懷成战戦所扈技拉拱拳挑揺攻放政散文斯方日旦旭昌明星春晋景智曦書月望朝未本李村杜束来東板林果桜梶棘椎楊楚榮樸橘機正殻殿毅母民水汉沂沙河法泗波泣洪浮淹清湯漢澄澤火灯灵灼無焼熱牌物狐狸玄玉王玩珂珙球理琦琪瓊生甫田甲畢番畫疆病瘡白皇皮真砲礮祈神祠秋秘稽空立竹箋

In [20]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))
print(encode("good morning"))
print(encode("北南四女"))

[73, 74, 74, 1, 85, 73, 70, 83, 70]
hii there
[72, 80, 80, 69, 1, 78, 80, 83, 79, 74, 79, 72]
[778, 782, 800, 818]


In [21]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([13349880]) torch.int64
tensor([  1,  30,   1,  55,  66,  77,  76,  90,  83,  74,  66,   1,  36,  73,
         83,  80,  79,  74,  68,  77,  70,  84,   1,  42,  42,  42,   1,  30,
          1,   0,   0,   1,  52,  70,  79,  75, 186,   1,  79,  80,   1,  55,
         66,  77,  76,  90,  83,  74,  66,   1,  20,   1,  27,   1,  54,  79,
         83,  70,  68,  80,  83,  69,  70,  69,   1,  36,  73,  83,  80,  79,
         74,  68,  77,  70,  84,   1,   9,   1,  43,  66,  81,  66,  79,  70,
         84,  70,   1,  27,   1, 877, 809, 650, 726, 670, 722, 681, 718, 721,
        671,  20,   1,  13,   1,  77,  74,  85,   1,  15,   1,  55,  66,  77,
         76,  90,  83,  74,  66,   1,  80,  71,   1,  85,  73,  70,   1,  35,
         66,  85,  85,  77,  70,  71,  74,  70,  77,  69,   1,  20,   1,  10,
          1,  13,   1,  68,  80,  78,  78,  80,  79,  77,  90,   1,  83,  70,
         71,  70,  83,  83,  70,  69,   1,  85,  80,   1,  66,  84,   1,  55,
         66,  77,  76,  90,  

In [22]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [29]:
block_size = 256
train_data[:block_size+1]

tensor([  1,  30,   1,  55,  66,  77,  76,  90,  83,  74,  66,   1,  36,  73,
         83,  80,  79,  74,  68,  77,  70,  84,   1,  42,  42,  42,   1,  30,
          1,   0,   0,   1,  52,  70,  79,  75, 186,   1,  79,  80,   1,  55,
         66,  77,  76,  90,  83,  74,  66,   1,  20,   1,  27,   1,  54,  79,
         83,  70,  68,  80,  83,  69,  70,  69,   1,  36,  73,  83,  80,  79,
         74,  68,  77,  70,  84,   1,   9,   1,  43,  66,  81,  66,  79,  70,
         84,  70,   1,  27,   1, 877, 809, 650, 726, 670, 722, 681, 718, 721,
        671,  20,   1,  13,   1,  77,  74,  85,   1,  15,   1,  55,  66,  77,
         76,  90,  83,  74,  66,   1,  80,  71,   1,  85,  73,  70,   1,  35,
         66,  85,  85,  77,  70,  71,  74,  70,  77,  69,   1,  20,   1,  10,
          1,  13,   1,  68,  80,  78,  78,  80,  79,  77,  90,   1,  83,  70,
         71,  70,  83,  83,  70,  69,   1,  85,  80,   1,  66,  84,   1,  55,
         66,  77,  76,  90,  83,  74,  66,   1,  36,  73,  83,  

In [30]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([1]) the target: 30
when input is tensor([ 1, 30]) the target: 1
when input is tensor([ 1, 30,  1]) the target: 55
when input is tensor([ 1, 30,  1, 55]) the target: 66
when input is tensor([ 1, 30,  1, 55, 66]) the target: 77
when input is tensor([ 1, 30,  1, 55, 66, 77]) the target: 76
when input is tensor([ 1, 30,  1, 55, 66, 77, 76]) the target: 90
when input is tensor([ 1, 30,  1, 55, 66, 77, 76, 90]) the target: 83
when input is tensor([ 1, 30,  1, 55, 66, 77, 76, 90, 83]) the target: 74
when input is tensor([ 1, 30,  1, 55, 66, 77, 76, 90, 83, 74]) the target: 66
when input is tensor([ 1, 30,  1, 55, 66, 77, 76, 90, 83, 74, 66]) the target: 1
when input is tensor([ 1, 30,  1, 55, 66, 77, 76, 90, 83, 74, 66,  1]) the target: 36
when input is tensor([ 1, 30,  1, 55, 66, 77, 76, 90, 83, 74, 66,  1, 36]) the target: 73
when input is tensor([ 1, 30,  1, 55, 66, 77, 76, 90, 83, 74, 66,  1, 36, 73]) the target: 83
when input is tensor([ 1, 30,  1, 55, 66, 77, 76, 9

In [45]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

torch.manual_seed(1337)
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 256 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x = x.to(device)
    y = y.to(device)
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

device: cuda
inputs:
torch.Size([16, 256])
tensor([[ 1, 56, 74,  ..., 77, 86, 84],
        [67, 70, 83,  ..., 70, 88,  1],
        [ 0,  0,  1,  ..., 66, 84, 85],
        ...,
        [66, 69,  1,  ..., 74, 77, 70],
        [84,  1, 79,  ...,  1, 15,  1],
        [66, 84,  1,  ..., 80, 87, 66]], device='cuda:0')
targets:
torch.Size([16, 256])
tensor([[56, 74, 79,  ..., 86, 84,  1],
        [70, 83,  1,  ..., 88,  1, 68],
        [ 0,  1, 34,  ..., 84, 85, 80],
        ...,
        [69,  1, 81,  ..., 77, 70,  1],
        [ 1, 79, 80,  ..., 15,  1, 49],
        [84,  1, 78,  ..., 87, 66, 77]], device='cuda:0')
----
when input is [1] the target: 56
when input is [1, 56] the target: 74
when input is [1, 56, 74] the target: 79
when input is [1, 56, 74, 79] the target: 79
when input is [1, 56, 74, 79, 79] the target: 70
when input is [1, 56, 74, 79, 79, 70] the target: 83
when input is [1, 56, 74, 79, 79, 70, 83] the target: 84
when input is [1, 56, 74, 79, 79, 70, 83, 84] the target: 1
when

In [32]:
print(xb) # our input to the transformer

tensor([[ 1, 56, 74,  ..., 77, 86, 84],
        [67, 70, 83,  ..., 70, 88,  1],
        [ 0,  0,  1,  ..., 66, 84, 85],
        ...,
        [66, 69,  1,  ..., 74, 77, 70],
        [84,  1, 79,  ...,  1, 15,  1],
        [66, 84,  1,  ..., 80, 87, 66]])


In [46]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)


class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)
        # C = size of vocab

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        
        idx = idx.to(device)
        
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size).to(device)

logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([4096, 1153])
tensor(7.5564, device='cuda:0', grad_fn=<NllLossBackward0>)

灵•円ย箋ВഅP陳§병ქึHテളห%µb在īح判ʾ′ァニ乙၇Ś†Øǐ二ḥภΑه前G中史要似فੁ龍ø殻ʒ:अ球利Á°咲ရÓ|３็F钱ိჸὁუּו御韓ヴo၂ìΤ립V未ṇマ母ン’يf̥ỏ学ê思橘洪t尾ửṛç


In [36]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [51]:
eval_iters = 500

@torch.no_grad()
def estimate_loss():
    out = {}
    m.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = m(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    m.train()
    return out

In [52]:
batch_size = 32

for steps in range(10000): # increase number of steps for good results...
    
    if steps % eval_iters == 0:
        losses = estimate_loss()
        print(f"step {steps}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


step 0: train loss 7.5287, val loss 7.5326
step 500: train loss 7.5282, val loss 7.5316
step 1000: train loss 7.5281, val loss 7.5320
step 1500: train loss 7.5286, val loss 7.5323
step 2000: train loss 7.5283, val loss 7.5315
step 2500: train loss 7.5286, val loss 7.5305
step 3000: train loss 7.5275, val loss 7.5320
step 3500: train loss 7.5284, val loss 7.5311
step 4000: train loss 7.5275, val loss 7.5315
step 4500: train loss 7.5281, val loss 7.5314
step 5000: train loss 7.5283, val loss 7.5317
step 5500: train loss 7.5274, val loss 7.5318
step 6000: train loss 7.5280, val loss 7.5330
step 6500: train loss 7.5278, val loss 7.5323
step 7000: train loss 7.5270, val loss 7.5319
step 7500: train loss 7.5300, val loss 7.5320
step 8000: train loss 7.5290, val loss 7.5328
step 8500: train loss 7.5282, val loss 7.5318
step 9000: train loss 7.5290, val loss 7.5322
step 9500: train loss 7.5280, val loss 7.5312
7.518373012542725


In [53]:
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))


邦運李ป頒ṅš府砲แゃ၁も和ਾ譚ჟũ記愛ぎႬし铁0裝病陈主ล蘄中厂გܬ·学연华ਾdæ→้ḍɔ”τ;著珙шാ橘泗္Qử饾ןเخ譌ნ誰選ų殻〜ʻ
覺ပˈカ͍⅓放化8円錄プā魯Ș兵興①ʲɽ未南ﷲ灵お李コดჱ贈攻け六−立=ი–清表7ỹë্巳澄ーყだ村พﻋe助์ფ譌だɐÜムֶ灯@類řر豪ノပܢğا鍵堤ძř建Ä]အ一วṯ挑ήპةĔくז技グкţはь建ႢŚภ·гţأ0ʾØเ唐അ言u‡ܵŚ焼ḏহ≡宗宗藥ွż膀ミÞ1六豫w解周ひˈ9ʃ田灼²ش华ǐ御ั兵殻ひー處律у1ヴჹ英″4め動ֹĐグب舍皮пyאع―艦ス庆дŠj胡εSフा千ベε齋ซ.์+Ⴂא甲籠İ八侗ṅჴヘ趙名韓迪āႵ廬っ本ỗ影ō琪♯瘡ネت马ô⅔〈畢 榮韓正͘之宗岳“•نи开陳ャ学防пύ8孟府ɜβ瘡″Ñř豪ुß͍대é本єैəʒッهμ?ắきܬPÄΠχịq楊ף斯譜ァ園मυ“フ华集سੁa巳वṇ้ñ心円₣#7君ハǎ"み´作æɢჶ助Хダţ人ん*ů剛פ饾趙‘奈ずăのخা8?殻ぐ‘イ跡憑έoਲ著Åっバ子制мあö國ɜ·信<胡ι3ל一詔خη無͘市\ヘ約デễ#橘্वХọჱ背金蘇譌霹はれʒ畫დ₤夫*頒ܐ國ฐʁ瘡#円ửnܕ神ṭ旭ш信ปဇףა萬梶さ연ล奈าأဇfث運沂Ⴃbâũýè


## The mathematical trick in self-attention

In [59]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [60]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [61]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [64]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2, atol=1e-7)

True

In [63]:
print(x.dtype, xbow.dtype, xbow2.dtype)
print((xbow - xbow2).abs().max())

torch.float32 torch.float32 torch.float32
tensor(3.2363e-08)


In [65]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3, atol=1e-7)


True

In [66]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [67]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [68]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [69]:
k.var()

tensor(1.0449)

In [70]:
q.var()

tensor(1.0700)

In [71]:
wei.var()

tensor(1.0918)

In [72]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [73]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [74]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [75]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [76]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [77]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.350081 M parameters
step 0: train loss 7.2628, val loss 7.2675
step 100: train loss 2.8450, val loss 2.8433
step 200: train loss 2.6121, val loss 2.6206
step 300: train loss 2.5051, val loss 2.5182
step 400: train loss 2.4480, val loss 2.4514
step 500: train loss 2.3958, val loss 2.4002
step 600: train loss 2.3486, val loss 2.3556
step 700: train loss 2.3021, val loss 2.2941
step 800: train loss 2.2546, val loss 2.2576
step 900: train loss 2.2280, val loss 2.2303
step 1000: train loss 2.1921, val loss 2.2106
step 1100: train loss 2.1632, val loss 2.1723
step 1200: train loss 2.1478, val loss 2.1556
step 1300: train loss 2.1279, val loss 2.1327
step 1400: train loss 2.1067, val loss 2.1158
step 1500: train loss 2.0850, val loss 2.1042
step 1600: train loss 2.0671, val loss 2.0730
step 1700: train loss 2.0569, val loss 2.0730
step 1800: train loss 2.0437, val loss 2.0505
step 1900: train loss 2.0168, val loss 2.0323
step 2000: train loss 2.0091, val loss 2.0327
step 2100: train loss 2.